global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'visionai_triton_scrape'
    static_configs:
      - targets: ['visionai-triton:8002']
  - job_name: 'visionai_inference_scrape'
    static_configs:
      - targets: ['visionai-inference:3003', 'visionai-inference-2:3005']


# Configure Prometheus to send metrics to Grafana Cloud
# remote_write:
#   - url: 'https://<YOUR-GRAFANA-CLOUD-PROMETHEUS-ENDPOINT>/api/prom/push'
#     basic_auth:
#       username: '<YOUR-API-KEY>'
#       password: ''
