global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'visionai_triton_scrape'
    static_configs:
      - targets: ['visionai-triton:8002']
  - job_name: 'visionai_api_scrape'
    static_configs:
      - targets: ['visionai-api:3003', 'visionai-api-2:3013']
